---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: example-hello
  labels:
    app: example-hello
spec:
  template:
    metadata:
      labels:
        app: example-hello
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: windows
      containers:
      - name: hello
        image: mcr.microsoft.com/windows/nanoserver:1809
        command:
        - cmd
        args:
        - /S
        - /C
        - FOR /L %N IN () DO @(echo %date% %time% & set & ping -n 15 127.0.0.1 >NUL) # NB we use ping because there is no timeout /T 15 /NOBREAK command in nanoserver.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
